# -*- coding: utf-8 -*-
"""4mar assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1byO1lvuGwYI6oiaVTHFSEkt1jMriaoT5
"""

!pip install plotly

import plotly.graph_objects as go

"""Q1. Load the "titanic" dataset using the load_dataset function of seaborn. Use Plotly express to plot a
scatter plot for age and fare columns in the titanic dataset.
"""

import seaborn as sns

titanic  = sns.load_dataset('titanic')

import plotly.express as px
fig =  px.scatter(x = titanic.age , y = titanic.fare)
fig.show()

"""Q2. Using the tips dataset in the Plotly library, plot a box plot using Plotly express."""

import seaborn as sns

import plotly.express as px
tips = sns.load_dataset('tips')
fig = px.box(x = tips.total_bill , y = tips.sex)
fig.show()

"""Q3. Using the tips dataset in the Plotly library, Plot a histogram for x= "sex" and y="total_bill" column in
the tips dataset. Also, use the "smoker" column with the pattern_shape parameter and the "day"
column with the color parameter.
"""

fig = px.histogram(x = tips.sex , y = tips.total_bill , pattern_shape = tips.smoker , color = tips.day )
fig.show()

"""Q4. Using the iris dataset in the Plotly library, Plot a scatter matrix plot, using the "species" column for
the color parameter.
Note: Use "sepal_length", "sepal_width", "petal_length", "petal_width" columns only with the
dimensions parameter.
"""

import seaborn as sns
iris = sns.load_dataset('iris')

import plotly.express as px

fig = px.scatter_matrix(iris ,dimensions = ["sepal_length", "sepal_width", "petal_length", "petal_width"] , color = 'species'  )
fig.show()

"""Q5. What is Distplot? Using Plotly express, plot a distplot.

A Distplot or distribution plot, depicts the variation in the data distribution. Seaborn Distplot represents the overall distribution of continuous data variables.

The Seaborn module along with the Matplotlib module is used to depict the distplot with different variations in it. The Distplot depicts the data by a histogram and a line in combination to it.
"""

import plotly.figure_factory as ff
import numpy as np
np.random.seed(1)

x = np.random.randn(1000)
hist_data = [x]
group_labels = ['distplot'] # name of the dataset

fig = ff.create_distplot(hist_data, group_labels)
fig.show()

